### ISSUE TITLE
Running `sovrin_client.test.training.getting_started.start_getting_started()` gives TypeError

### ISSUE THREAD

**Issue by hidde-jan** [hyperledger/indy-client#207]
Sovrin-client and sovrin-node installed through  `pip install sovrin-client sovrin-node`.

This is the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hidde-jan/src/sovrin/lib/python3.5/site-packages/sovrin_client/test/training/getting_started.py", line 86, in start_getting_started
    main()
  File "/home/hidde-jan/src/sovrin/lib/python3.5/site-packages/sovrin_client/test/training/getting_started.py", line 80, in main
    withNode=False)
  File "/home/hidde-jan/src/sovrin/lib/python3.5/site-packages/sovrin_client/cli/cli.py", line 113, in __init__
    super().__init__(*args, **kwargs)
  File "/home/hidde-jan/src/sovrin/lib/python3.5/site-packages/plenum/cli/cli.py", line 264, in __init__
    self.print("\n{}-CLI (c) 2017 Evernym, Inc.".format(self.properName))
  File "/home/hidde-jan/src/sovrin/lib/python3.5/site-packages/sovrin_client/cli/cli.py", line 1726, in print
    super().print(msg, token=token, newline=newline)
  File "/home/hidde-jan/src/sovrin/lib/python3.5/site-packages/plenum/cli/cli.py", line 620, in print
    self.cli.run_in_terminal(part)
  File "/home/hidde-jan/src/sovrin/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 641, in run_in_terminal
    result = func()
  File "/home/hidde-jan/src/sovrin/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 790, in print_tokens
    print_tokens(self.output, tokens, style or self.application.style)
  File "/home/hidde-jan/src/sovrin/lib/python3.5/site-packages/prompt_toolkit/renderer.py", line 515, in print_tokens
    attrs = attrs_for_token[token]
  File "/home/hidde-jan/src/sovrin/lib/python3.5/site-packages/prompt_toolkit/renderer.py", line 219, in __missing__
    result = self.get_style_for_token(token)
  File "/home/hidde-jan/src/sovrin/lib/python3.5/site-packages/prompt_toolkit/styles/from_dict.py", line 143, in get_attrs_for_token
    for token in split_token_in_parts(token):
  File "/home/hidde-jan/src/sovrin/lib/python3.5/site-packages/prompt_toolkit/styles/utils.py", line 17, in split_token_in_parts
    for part in token + (':', ):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'tuple'
```

**Comment by dhh1128** [comment]
@AlexanderShekhovcov do you have any ideas why this might be happening for Jan?
